import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import { Header } from "@/components/header";
import { AutoBreadcrumb } from "@/components/auto-breadcrumb";

const plus_jakarta_sans = Plus_Jakarta_Sans({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${plus_jakarta_sans.className} antialiased`}
      >
        <div className="min-h-screen flex bg-neutral-50 text-neutral-900">
          <Sidebar />
          <div className="flex-1 lg:pl-64">
            <Header />
            <main className="min-h-[calc(100vh-64px)] mt-16 relative">
              <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 h-full py-6">
                <AutoBreadcrumb />
                {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
